# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4989f,-0.0578f,0f,-0.1276f,-0.0578f,1.4989f,0f,3.3076f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7494f,-0.0289f,0f,0.6484f,-0.0289f,0.7494f,0f,2.6495f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7494f,-0.0289f,0f,-0.1011f,-0.0289f,0.7494f,0f,2.6206f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0617f,-0.0409f,0f,0.9678f,-0.0409f,1.0617f,0f,2.4742f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0617f,-0.0409f,0f,-0.0939f,-0.0409f,1.0617f,0f,2.4333f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7494f,-0.012f,0f,0.6676f,-0.0289f,0.3123f,0f,2.1499f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7494f,-0.012f,0f,-0.0818f,-0.0289f,0.3123f,0f,2.121f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8744f,-0.0241f,0f,-0.0577f,-0.0337f,0.6245f,0f,1.4965f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8744f,-0.0241f,0f,0.8166f,-0.0337f,0.6245f,0f,1.5302f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8119f,-0.0286f,-0.0116f,1.7813f,-0.0313f,0.743f,0.3022f,2.4661f,0f,0.3276f,-0.6863f,0.1562f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8119f,-0.0088f,-0.0116f,1.7901f,-0.0313f,0.2286f,0.3022f,2.2375f,0f,0.1008f,-0.6863f,0.0554f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.1249f,-0.0242f,-0.0097f,2.0073f,-0.0048f,0.6287f,0.2518f,1.4697f,0f,0.2772f,-0.572f,-0.3546f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8744f,-0.0375f,-0.0136f,1.891f,-0.0337f,0.9716f,0.3525f,1.2431f,0f,0.4284f,-0.8007f,-0.3158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6245f,-0.0154f,-0.0097f,1.7795f,-0.0241f,0.4001f,0.2518f,0.8886f,0f,0.1764f,-0.572f,-0.6066f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2498f,-0.011f,-0.0039f,1.7291f,-0.0096f,0.2858f,0.1007f,0.5752f,0f,0.126f,-0.2288f,-0.6754f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2498f,-0.011f,-0.0039f,1.2875f,-0.0096f,0.2858f,0.1007f,0.6727f,0f,0.126f,-0.2288f,-0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2498f,-0.0132f,-0.0039f,1.8523f,-0.0096f,0.3429f,0.1007f,0.6236f,0f,0.1512f,-0.2288f,-0.9293f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2498f,-0.011f,-0.0039f,1.7213f,-0.0096f,0.2858f,0.1007f,0.7767f,0f,0.126f,-0.2288f,-1.1329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8744f,-0.0375f,0.0136f,-1.1233f,-0.0337f,0.9716f,-0.3525f,1.5556f,0f,-0.4284f,-0.8007f,1.1006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.1249f,-0.0242f,0.0097f,-2.0023f,-0.0048f,0.6287f,-0.2518f,1.643f,0f,-0.2772f,-0.572f,0.9106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2498f,-0.011f,0.0039f,-1.1003f,-0.0096f,0.2858f,-0.1007f,0.9589f,0f,-0.126f,-0.2288f,1.2954f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2498f,-0.011f,0.0039f,-1.5955f,-0.0096f,0.2858f,-0.1007f,0.8253f,0f,-0.126f,-0.2288f,1.3458f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2498f,-0.0132f,0.0039f,-1.7143f,-0.0096f,0.3429f,-0.1007f,0.6626f,0f,-0.1512f,-0.2288f,1.1422f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2498f,-0.011f,0.0039f,-1.5878f,-0.0096f,0.2858f,-0.1007f,0.6239f,0f,-0.126f,-0.2288f,0.8882f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6245f,-0.0154f,0.0097f,-1.2309f,-0.0241f,0.4001f,-0.2518f,1.1003f,0f,-0.1764f,-0.572f,1.1626f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8119f,-0.0088f,0.0116f,-1.1598f,-0.0313f,0.2286f,-0.3022f,2.502f,0f,-0.1008f,-0.6863f,0.615f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8119f,-0.0286f,0.0116f,-1.1686f,-0.0313f,0.743f,-0.3022f,2.7306f,0f,-0.3276f,-0.6863f,0.5143f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8744f,-0.0529f,-0.0136f,-0.2467f,-0.0337f,1.3717f,0.3525f,-0.0916f,0f,0.6048f,-0.8007f,-0.1845f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8744f,-0.0529f,0.0136f,1.1115f,-0.0337f,1.3717f,-0.3525f,0.3696f,0f,-0.6048f,-0.8007f,0.9998f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000464033,"py":-0.0024079583,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args