# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4988f,0.0595f,0f,0.1315f,0.0595f,1.4988f,0f,3.3124f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7494f,0.0298f,0f,0.8536f,0.0298f,0.7494f,0f,2.5956f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7494f,0.0298f,0f,0.1042f,0.0298f,0.7494f,0f,2.6254f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0617f,0.0422f,0f,1.1585f,0.0422f,1.0617f,0f,2.3959f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0617f,0.0422f,0f,0.0968f,0.0422f,1.0617f,0f,2.4381f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7494f,0.0124f,0f,0.8338f,0.0298f,0.3123f,0f,2.096f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7494f,0.0124f,0f,0.0844f,0.0298f,0.3123f,0f,2.1258f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8743f,0.0248f,0f,0.0596f,0.0347f,0.6245f,0f,1.5013f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8743f,0.0248f,0f,0.9339f,0.0347f,0.6245f,0f,1.4666f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8119f,0.0295f,-0.012f,1.9848f,0.0322f,0.743f,-0.3021f,2.7271f,0f,-0.3276f,-0.6863f,0.5089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8119f,0.0091f,-0.012f,1.9757f,0.0322f,0.2286f,-0.3021f,2.4985f,0f,-0.1008f,-0.6863f,0.6097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.1249f,0.025f,-0.01f,2.1302f,0.005f,0.6287f,-0.2518f,1.6657f,0f,-0.2772f,-0.572f,0.9053f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8743f,0.0386f,-0.014f,2.0005f,0.0347f,0.9716f,-0.3525f,1.5496f,0f,-0.4284f,-0.8007f,1.0953f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6245f,0.0159f,-0.01f,1.8577f,0.0248f,0.4001f,-0.2518f,1.1042f,0f,-0.1764f,-0.572f,1.1573f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2498f,0.0114f,-0.004f,1.7849f,0.0099f,0.2858f,-0.1007f,0.8461f,0f,-0.126f,-0.2288f,1.3405f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2498f,0.0114f,-0.004f,1.3523f,0.0099f,0.2858f,-0.1007f,0.9777f,0f,-0.126f,-0.2288f,1.2901f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2498f,0.0136f,-0.004f,1.9036f,0.0099f,0.3429f,-0.1007f,0.6832f,0f,-0.1512f,-0.2288f,1.1369f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2498f,0.0114f,-0.004f,1.7769f,0.0099f,0.2858f,-0.1007f,0.6446f,0f,-0.126f,-0.2288f,0.8829f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8743f,0.0386f,0.014f,-1.0141f,0.0347f,0.9716f,0.3525f,1.2407f,0f,0.4284f,-0.8007f,-0.3105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.1249f,0.025f,0.01f,-1.8796f,0.005f,0.6287f,0.2518f,1.4972f,0f,0.2772f,-0.572f,-0.3493f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2498f,0.0114f,0.004f,-1.0358f,0.0099f,0.2858f,0.1007f,0.6943f,0f,0.126f,-0.2288f,-0.6197f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2498f,0.0114f,0.004f,-1.54f,0.0099f,0.2858f,0.1007f,0.5999f,0f,0.126f,-0.2288f,-0.6701f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2498f,0.0136f,0.004f,-1.6631f,0.0099f,0.3429f,0.1007f,0.6484f,0f,0.1512f,-0.2288f,-0.924f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2498f,0.0114f,0.004f,-1.532f,0.0099f,0.2858f,0.1007f,0.8013f,0f,0.126f,-0.2288f,-1.1276f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6245f,0.0159f,0.01f,-1.1529f,0.0248f,0.4001f,0.2518f,0.8959f,0f,0.1764f,-0.572f,-0.6013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8119f,0.0091f,0.012f,-0.9745f,0.0322f,0.2286f,0.3021f,2.2374f,0f,0.1008f,-0.6863f,0.0607f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8119f,0.0295f,0.012f,-0.9654f,0.0322f,0.743f,0.3021f,2.466f,0f,0.3276f,-0.6863f,0.1615f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8743f,0.0545f,-0.014f,-0.2369f,0.0347f,1.3716f,-0.3525f,0.3357f,0f,-0.6048f,-0.8007f,0.9746f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8743f,0.0545f,0.014f,1.1212f,0.0347f,1.3716f,0.3525f,-0.1164f,0f,0.6048f,-0.8007f,-0.2097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000492514,"py":0.0024807263,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args