# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.499f,0.0549f,0f,0.1213f,0.0549f,1.499f,0f,3.3126f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7495f,0.0275f,0f,0.8456f,0.0275f,0.7495f,0f,2.5981f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7495f,0.0275f,0f,0.0961f,0.0275f,0.7495f,0f,2.6255f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0618f,0.0389f,0f,1.1511f,0.0389f,1.0618f,0f,2.3993f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0618f,0.0389f,0f,0.0893f,0.0389f,1.0618f,0f,2.4382f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7495f,0.0114f,0f,0.8273f,0.0275f,0.3123f,0f,2.0984f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7495f,0.0114f,0f,0.0778f,0.0275f,0.3123f,0f,2.1259f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8744f,0.0229f,0f,0.055f,0.032f,0.6246f,0f,1.5013f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8744f,0.0229f,0f,0.9294f,0.032f,0.6246f,0f,1.4692f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.812f,0.0279f,-0.0095f,1.9749f,0.0297f,0.7619f,-0.2591f,2.6941f,0f,-0.2809f,-0.7038f,0.4954f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.812f,0.0086f,-0.0095f,1.9663f,0.0297f,0.2344f,-0.2591f,2.4597f,0f,-0.0864f,-0.7038f,0.5818f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.1249f,0.0236f,-0.0079f,2.1229f,0.0046f,0.6447f,-0.2159f,1.6107f,0f,-0.2377f,-0.5865f,0.8257f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8744f,0.0365f,-0.0111f,1.9931f,0.032f,0.9963f,-0.3023f,1.4827f,0f,-0.3673f,-0.821f,1.0078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6246f,0.015f,-0.0079f,1.8515f,0.0229f,0.4102f,-0.2159f,1.0338f,0f,-0.1513f,-0.5865f,1.0418f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2498f,0.0107f,-0.0032f,1.7791f,0.0092f,0.293f,-0.0864f,0.7647f,0f,-0.108f,-0.2346f,1.2085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2498f,0.0107f,-0.0032f,1.3462f,0.0092f,0.293f,-0.0864f,0.8979f,0f,-0.108f,-0.2346f,1.1652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2498f,0.0129f,-0.0032f,1.8988f,0.0092f,0.3516f,-0.0864f,0.6151f,0f,-0.1296f,-0.2346f,0.9955f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2498f,0.0107f,-0.0032f,1.7728f,0.0092f,0.293f,-0.0864f,0.5919f,0f,-0.108f,-0.2346f,0.7393f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8744f,0.0365f,0.0111f,-1.0184f,0.032f,0.9963f,0.3023f,1.2254f,0f,0.3673f,-0.821f,-0.1983f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.1249f,0.0236f,0.0079f,-1.8848f,0.0046f,0.6447f,0.2159f,1.4765f,0f,0.2377f,-0.5865f,-0.2508f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2498f,0.0107f,0.0032f,-1.039f,0.0092f,0.293f,0.0864f,0.661f,0f,0.108f,-0.2346f,-0.473f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2498f,0.0107f,0.0032f,-1.543f,0.0092f,0.293f,0.0864f,0.5621f,0f,0.108f,-0.2346f,-0.5163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2498f,0.0129f,0.0032f,-1.6669f,0.0092f,0.3516f,0.0864f,0.5944f,0f,0.1296f,-0.2346f,-0.7725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2498f,0.0107f,0.0032f,-1.5367f,0.0092f,0.293f,0.0864f,0.7348f,0f,0.108f,-0.2346f,-0.9854f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6246f,0.015f,0.0079f,-1.1567f,0.0229f,0.4102f,0.2159f,0.863f,0f,0.1513f,-0.5865f,-0.4669f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.812f,0.0086f,0.0095f,-0.9811f,0.0297f,0.2344f,0.2591f,2.2434f,0f,0.0864f,-0.7038f,0.1103f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.812f,0.0279f,0.0095f,-0.9725f,0.0297f,0.7619f,0.2591f,2.4778f,0f,0.2809f,-0.7038f,0.1968f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8744f,0.0515f,-0.0111f,-0.2402f,0.032f,1.4066f,-0.3023f,0.2728f,0f,-0.5186f,-0.821f,0.9036f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8744f,0.0515f,0.0111f,1.1213f,0.032f,1.4066f,0.3023f,-0.1192f,0f,0.5186f,-0.821f,-0.1119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000418987,"py":0.0022881383,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args