# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4994f,0.0424f,0f,0.0936f,0.0424f,1.4994f,0f,3.3129f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7497f,0.0212f,0f,0.8239f,0.0212f,0.7497f,0f,2.6045f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7497f,0.0212f,0f,0.0742f,0.0212f,0.7497f,0f,2.6257f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0621f,0.03f,0f,1.1309f,0.03f,1.0621f,0f,2.4083f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0621f,0.03f,0f,0.0689f,0.03f,1.0621f,0f,2.4383f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7497f,0.0088f,0f,0.8097f,0.0212f,0.3124f,0f,2.1047f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7497f,0.0088f,0f,0.06f,0.0212f,0.3124f,0f,2.1259f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8747f,0.0177f,0f,0.0424f,0.0247f,0.6248f,0f,1.5012f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8747f,0.0177f,0f,0.917f,0.0247f,0.6248f,0f,1.4765f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8122f,0.0222f,-0.0054f,1.9506f,0.0229f,0.7856f,-0.1902f,2.6514f,0f,-0.2061f,-0.7255f,0.4696f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8122f,0.0068f,-0.0054f,1.9438f,0.0229f,0.2417f,-0.1902f,2.4096f,0f,-0.0634f,-0.7255f,0.533f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.125f,0.0188f,-0.0045f,2.1069f,0.0035f,0.6647f,-0.1585f,1.5425f,0f,-0.1744f,-0.6046f,0.6945f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8747f,0.029f,-0.0063f,1.9777f,0.0247f,1.0273f,-0.2219f,1.3964f,0f,-0.2695f,-0.8464f,0.863f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6248f,0.012f,-0.0045f,1.8399f,0.0177f,0.423f,-0.1585f,0.9452f,0f,-0.111f,-0.6046f,0.8531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2499f,0.0085f,-0.0018f,1.7693f,0.0071f,0.3022f,-0.0634f,0.6607f,0f,-0.0793f,-0.2418f,0.9928f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2499f,0.0085f,-0.0018f,1.3354f,0.0071f,0.3022f,-0.0634f,0.7939f,0f,-0.0793f,-0.2418f,0.9611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2499f,0.0102f,-0.0018f,1.8908f,0.0071f,0.3626f,-0.0634f,0.5333f,0f,-0.0951f,-0.2418f,0.7668f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2499f,0.0085f,-0.0018f,1.7658f,0.0071f,0.3022f,-0.0634f,0.5339f,0f,-0.0793f,-0.2418f,0.5092f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8747f,0.029f,0.0063f,-1.0287f,0.0247f,1.0273f,0.2219f,1.2117f,0f,0.2695f,-0.8464f,-0.0228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.125f,0.0188f,0.0045f,-1.8973f,0.0035f,0.6647f,0.1585f,1.4494f,0f,0.1744f,-0.6046f,-0.0961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2499f,0.0085f,0.0018f,-1.0453f,0.0071f,0.3022f,0.0634f,0.6232f,0f,0.0793f,-0.2418f,-0.2418f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2499f,0.0085f,0.0018f,-1.5486f,0.0071f,0.3022f,0.0634f,0.5165f,0f,0.0793f,-0.2418f,-0.2735f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2499f,0.0102f,0.0018f,-1.6734f,0.0071f,0.3626f,0.0634f,0.523f,0f,0.0951f,-0.2418f,-0.5312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2499f,0.0085f,0.0018f,-1.545f,0.0071f,0.3022f,0.0634f,0.6433f,0f,0.0793f,-0.2418f,-0.7571f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6248f,0.012f,0.0045f,-1.1647f,0.0177f,0.423f,0.1585f,0.8239f,0f,0.111f,-0.6046f,-0.2547f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8122f,0.0068f,0.0054f,-0.9992f,0.0229f,0.2417f,0.1902f,2.2549f,0f,0.0634f,-0.7255f,0.1863f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8122f,0.0222f,0.0054f,-0.9924f,0.0229f,0.7856f,0.1902f,2.4966f,0f,0.2061f,-0.7255f,0.2497f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8747f,0.041f,-0.0063f,-0.245f,0.0247f,1.4504f,-0.2219f,0.1826f,0f,-0.3805f,-0.8464f,0.7858f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8747f,0.041f,0.0063f,1.1224f,0.0247f,1.4504f,0.2219f,-0.1077f,0f,0.3805f,-0.8464f,0.0406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000249351,"py":0.001765295,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args