# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4999f,0.0179f,0f,0.0396f,0.0179f,1.4999f,0f,3.313f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7499f,0.009f,0f,0.7813f,0.009f,0.7499f,0f,2.6166f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7499f,0.009f,0f,0.0314f,0.009f,0.7499f,0f,2.6256f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0624f,0.0127f,0f,1.0916f,0.0127f,1.0624f,0f,2.4254f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0624f,0.0127f,0f,0.0291f,0.0127f,1.0624f,0f,2.4381f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7499f,0.0037f,0f,0.7753f,0.009f,0.3125f,0f,2.1166f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7499f,0.0037f,0f,0.0254f,0.009f,0.3125f,0f,2.1256f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8749f,0.0075f,0f,0.0179f,0.0105f,0.625f,0f,1.5006f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8749f,0.0075f,0f,0.8929f,0.0105f,0.625f,0f,1.4902f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8124f,0.0096f,-0.0012f,1.9063f,0.0097f,0.8051f,-0.1008f,2.6118f,0f,-0.1092f,-0.7432f,0.4293f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8124f,0.003f,-0.0012f,1.9034f,0.0097f,0.2477f,-0.1008f,2.3641f,0f,-0.0336f,-0.7432f,0.4629f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.125f,0.0081f,-0.001f,2.0804f,0.0015f,0.6812f,-0.084f,1.4865f,0f,-0.0924f,-0.6193f,0.5186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8749f,0.0126f,-0.0014f,1.9534f,0.0105f,1.0528f,-0.1176f,1.319f,0f,-0.1428f,-0.8671f,0.6676f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.625f,0.0052f,-0.001f,1.823f,0.0075f,0.4335f,-0.084f,0.8702f,0f,-0.0588f,-0.6193f,0.6026f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.25f,0.0037f,-0.0004f,1.7569f,0.003f,0.3096f,-0.0336f,0.5697f,0f,-0.042f,-0.2477f,0.7065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.25f,0.0037f,-0.0004f,1.3209f,0.003f,0.3096f,-0.0336f,0.6988f,0f,-0.042f,-0.2477f,0.6897f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.25f,0.0044f,-0.0004f,1.8808f,0.003f,0.3716f,-0.0336f,0.4727f,0f,-0.0504f,-0.2477f,0.4672f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.25f,0.0037f,-0.0004f,1.7561f,0.003f,0.3096f,-0.0336f,0.5025f,0f,-0.042f,-0.2477f,0.2111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8749f,0.0126f,0.0014f,-1.0481f,0.0105f,1.0528f,0.1176f,1.212f,0f,0.1428f,-0.8671f,0.1977f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.125f,0.0081f,0.001f,-1.9206f,0.0015f,0.6812f,0.084f,1.4251f,0f,0.0924f,-0.6193f,0.0991f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.25f,0.0037f,0.0004f,-1.0554f,0.003f,0.3096f,0.0336f,0.6011f,0f,0.042f,-0.2477f,0.0518f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.25f,0.0037f,0.0004f,-1.5568f,0.003f,0.3096f,0.0336f,0.4833f,0f,0.042f,-0.2477f,0.035f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.25f,0.0044f,0.0004f,-1.6822f,0.003f,0.3716f,0.0336f,0.4564f,0f,0.0504f,-0.2477f,-0.2212f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.25f,0.0037f,0.0004f,-1.556f,0.003f,0.3096f,0.0336f,0.5505f,0f,0.042f,-0.2477f,-0.4605f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.625f,0.0052f,0.001f,-1.1781f,0.0075f,0.4335f,0.084f,0.7968f,0f,0.0588f,-0.6193f,0.015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8124f,0.003f,0.0012f,-1.0354f,0.0097f,0.2477f,0.1008f,2.2732f,0f,0.0336f,-0.7432f,0.2786f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8124f,0.0096f,0.0012f,-1.0325f,0.0097f,0.8051f,0.1008f,2.5209f,0f,0.1092f,-0.7432f,0.3122f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8749f,0.0178f,-0.0014f,-0.249f,0.0105f,1.4863f,-0.1176f,0.084f,0f,-0.2016f,-0.8671f,0.6262f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8749f,0.0178f,0.0014f,1.1243f,0.0105f,1.4863f,0.1176f,-0.0663f,0f,0.2016f,-0.8671f,0.2313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000044619,"py":0.0007468048,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args