# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4994f,-0.0424f,0f,-0.0935f,-0.0424f,1.4994f,0f,3.3094f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7497f,-0.0212f,0f,0.6756f,-0.0212f,0.7497f,0f,2.6434f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7497f,-0.0212f,0f,-0.0741f,-0.0212f,0.7497f,0f,2.6222f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0621f,-0.03f,0f,0.9933f,-0.03f,1.0621f,0f,2.4648f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0621f,-0.03f,0f,-0.0688f,-0.03f,1.0621f,0f,2.4348f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7497f,-0.0088f,0f,0.6897f,-0.0212f,0.3124f,0f,2.1436f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7497f,-0.0088f,0f,-0.06f,-0.0212f,0.3124f,0f,2.1224f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8747f,-0.0177f,0f,-0.0423f,-0.0247f,0.6248f,0f,1.4976f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8747f,-0.0177f,0f,0.8323f,-0.0247f,0.6248f,0f,1.5224f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8122f,-0.0227f,-0.0028f,1.8037f,-0.0229f,0.8048f,0.1008f,2.5495f,0f,0.1092f,-0.7432f,0.3117f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8122f,-0.007f,-0.0028f,1.8107f,-0.0229f,0.2476f,0.1008f,2.3018f,0f,0.0336f,-0.7432f,0.278f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.125f,-0.0192f,-0.0024f,2.0224f,-0.0035f,0.681f,0.084f,1.4488f,0f,0.0924f,-0.6193f,0.0985f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8747f,-0.0297f,-0.0033f,1.9031f,-0.0247f,1.0524f,0.1176f,1.2428f,0f,0.1428f,-0.8671f,0.1971f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6248f,-0.0122f,-0.0024f,1.79f,-0.0177f,0.4334f,0.084f,0.8227f,0f,0.0588f,-0.6193f,0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2499f,-0.0087f,-0.0009f,1.7365f,-0.0071f,0.3095f,0.0336f,0.503f,0f,0.042f,-0.2477f,0.0344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2499f,-0.0087f,-0.0009f,1.2956f,-0.0071f,0.3095f,0.0336f,0.6144f,0f,0.042f,-0.2477f,0.0512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2499f,-0.0105f,-0.0009f,1.8622f,-0.0071f,0.3714f,0.0336f,0.4782f,0f,0.0504f,-0.2477f,-0.2217f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2499f,-0.0087f,-0.0009f,1.7346f,-0.0071f,0.3095f,0.0336f,0.5701f,0f,0.042f,-0.2477f,-0.4611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8747f,-0.0297f,0.0033f,-1.0997f,-0.0247f,1.0524f,-0.1176f,1.3008f,0f,-0.1428f,-0.8671f,0.6682f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.125f,-0.0192f,0.0024f,-1.9791f,-0.0035f,0.681f,-0.084f,1.445f,0f,-0.0924f,-0.6193f,0.5191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2499f,-0.0087f,0.0009f,-1.082f,-0.0071f,0.3095f,-0.0336f,0.6733f,0f,-0.042f,-0.2477f,0.6903f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2499f,-0.0087f,0.0009f,-1.5783f,-0.0071f,0.3095f,-0.0336f,0.5354f,0f,-0.042f,-0.2477f,0.7071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2499f,-0.0105f,0.0009f,-1.7005f,-0.0071f,0.3714f,-0.0336f,0.4363f,0f,-0.0504f,-0.2477f,0.4678f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2499f,-0.0087f,0.0009f,-1.5764f,-0.0071f,0.3095f,-0.0336f,0.4682f,0f,-0.042f,-0.2477f,0.2116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6248f,-0.0122f,0.0024f,-1.2119f,-0.0177f,0.4334f,-0.084f,0.8471f,0f,-0.0588f,-0.6193f,0.6032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8122f,-0.007f,0.0028f,-1.1292f,-0.0229f,0.2476f,-0.1008f,2.3448f,0f,-0.0336f,-0.7432f,0.4634f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8122f,-0.0227f,0.0028f,-1.1362f,-0.0229f,0.8048f,-0.1008f,2.5925f,0f,-0.1092f,-0.7432f,0.4298f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8747f,-0.042f,-0.0033f,-0.2483f,-0.0247f,1.4858f,0.1176f,-0.063f,0f,0.2016f,-0.8671f,0.2397f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8747f,-0.042f,0.0033f,1.1223f,-0.0247f,1.4858f,-0.1176f,0.1108f,0f,-0.2016f,-0.8671f,0.6346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000249351,"py":-0.001765295,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args