# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.499f,-0.0549f,0f,-0.1212f,-0.0549f,1.499f,0f,3.308f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7495f,-0.0275f,0f,0.6534f,-0.0275f,0.7495f,0f,2.6484f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7495f,-0.0275f,0f,-0.0961f,-0.0275f,0.7495f,0f,2.621f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0618f,-0.0389f,0f,0.9726f,-0.0389f,1.0618f,0f,2.4725f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0618f,-0.0389f,0f,-0.0892f,-0.0389f,1.0618f,0f,2.4336f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7495f,-0.0114f,0f,0.6717f,-0.0275f,0.3123f,0f,2.1487f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7495f,-0.0114f,0f,-0.0778f,-0.0275f,0.3123f,0f,2.1213f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8744f,-0.0229f,0f,-0.0549f,-0.032f,0.6246f,0f,1.4967f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8744f,-0.0229f,0f,0.8195f,-0.032f,0.6246f,0f,1.5287f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.812f,-0.0288f,-0.007f,1.7841f,-0.0297f,0.7854f,0.1901f,2.5147f,0f,0.2061f,-0.7255f,0.2477f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.812f,-0.0089f,-0.007f,1.7929f,-0.0297f,0.2417f,0.1901f,2.273f,0f,0.0634f,-0.7255f,0.1842f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.1249f,-0.0243f,-0.0058f,2.0107f,-0.0046f,0.6646f,0.1584f,1.4499f,0f,0.1744f,-0.6046f,-0.0982f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8744f,-0.0376f,-0.0081f,1.8936f,-0.032f,1.0271f,0.2218f,1.2324f,0f,0.2695f,-0.8464f,-0.0248f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6246f,-0.0155f,-0.0058f,1.783f,-0.0229f,0.4229f,0.1584f,0.8366f,0f,0.111f,-0.6046f,-0.2567f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2498f,-0.0111f,-0.0023f,1.7322f,-0.0092f,0.3021f,0.0634f,0.5164f,0f,0.0793f,-0.2418f,-0.2755f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2498f,-0.0111f,-0.0023f,1.2906f,-0.0092f,0.3021f,0.0634f,0.6212f,0f,0.0793f,-0.2418f,-0.2438f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2498f,-0.0133f,-0.0023f,1.857f,-0.0092f,0.3625f,0.0634f,0.5239f,0f,0.0951f,-0.2418f,-0.5332f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2498f,-0.0111f,-0.0023f,1.7276f,-0.0092f,0.3021f,0.0634f,0.6432f,0f,0.0793f,-0.2418f,-0.7592f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8744f,-0.0376f,0.0081f,-1.1142f,-0.032f,1.0271f,-0.2218f,1.3919f,0f,-0.2695f,-0.8464f,0.8651f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.1249f,-0.0243f,0.0058f,-1.9941f,-0.0046f,0.6646f,-0.1584f,1.5095f,0f,-0.1744f,-0.6046f,0.6966f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2498f,-0.0111f,0.0023f,-1.0915f,-0.0092f,0.3021f,-0.0634f,0.7719f,0f,-0.0793f,-0.2418f,0.9631f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2498f,-0.0111f,0.0023f,-1.5868f,-0.0092f,0.3021f,-0.0634f,0.6328f,0f,-0.0793f,-0.2418f,0.9949f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2498f,-0.0133f,0.0023f,-1.7072f,-0.0092f,0.3625f,-0.0634f,0.5044f,0f,-0.0951f,-0.2418f,0.7689f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2498f,-0.0111f,0.0023f,-1.5821f,-0.0092f,0.3021f,-0.0634f,0.506f,0f,-0.0793f,-0.2418f,0.5112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6246f,-0.0155f,0.0058f,-1.2225f,-0.0229f,0.4229f,-0.1584f,0.9328f,0f,-0.111f,-0.6046f,0.8551f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.812f,-0.0089f,0.007f,-1.1513f,-0.0297f,0.2417f,-0.1901f,2.4031f,0f,-0.0634f,-0.7255f,0.5351f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.812f,-0.0288f,0.007f,-1.1601f,-0.0297f,0.7854f,-0.1901f,2.6448f,0f,-0.2061f,-0.7255f,0.4717f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8744f,-0.0531f,-0.0081f,-0.2469f,-0.032f,1.45f,0.2218f,-0.0912f,0f,0.3805f,-0.8464f,0.0565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8744f,-0.0531f,0.0081f,1.1178f,-0.032f,1.45f,-0.2218f,0.2147f,0f,-0.3805f,-0.8464f,0.8016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000418987,"py":-0.0022881383,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args