# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4988f,-0.0595f,0f,-0.1314f,-0.0595f,1.4988f,0f,3.3074f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7494f,-0.0298f,0f,0.6453f,-0.0298f,0.7494f,0f,2.6502f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7494f,-0.0298f,0f,-0.1041f,-0.0298f,0.7494f,0f,2.6205f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0617f,-0.0422f,0f,0.965f,-0.0422f,1.0617f,0f,2.4753f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0617f,-0.0422f,0f,-0.0967f,-0.0422f,1.0617f,0f,2.4331f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7494f,-0.0124f,0f,0.6651f,-0.0298f,0.3123f,0f,2.1506f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7494f,-0.0124f,0f,-0.0843f,-0.0298f,0.3123f,0f,2.1208f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8743f,-0.0248f,0f,-0.0595f,-0.0347f,0.6245f,0f,1.4963f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8743f,-0.0248f,0f,0.8148f,-0.0347f,0.6245f,0f,1.5311f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8119f,-0.0303f,-0.0103f,1.7777f,-0.0322f,0.7618f,0.2591f,2.4867f,0f,0.2809f,-0.7038f,0.1929f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8119f,-0.0093f,-0.0103f,1.787f,-0.0322f,0.2344f,0.2591f,2.2523f,0f,0.0864f,-0.7038f,0.1065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.1249f,-0.0256f,-0.0086f,2.006f,-0.005f,0.6446f,0.2159f,1.4609f,0f,0.2377f,-0.5865f,-0.2547f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8743f,-0.0396f,-0.012f,1.8898f,-0.0347f,0.9962f,0.3023f,1.2369f,0f,0.3673f,-0.821f,-0.2022f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6245f,-0.0163f,-0.0086f,1.7795f,-0.0248f,0.4102f,0.2159f,0.865f,0f,0.1513f,-0.5865f,-0.4707f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2498f,-0.0116f,-0.0034f,1.7296f,-0.0099f,0.293f,0.0864f,0.5479f,0f,0.108f,-0.2346f,-0.5201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2498f,-0.0116f,-0.0034f,1.2878f,-0.0099f,0.293f,0.0864f,0.6477f,0f,0.108f,-0.2346f,-0.4769f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2498f,-0.014f,-0.0034f,1.8534f,-0.0099f,0.3516f,0.0864f,0.5806f,0f,0.1296f,-0.2346f,-0.7763f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2498f,-0.0116f,-0.0034f,1.7227f,-0.0099f,0.293f,0.0864f,0.7206f,0f,0.108f,-0.2346f,-0.9893f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8743f,-0.0396f,0.012f,-1.1224f,-0.0347f,0.9962f,-0.3023f,1.4849f,0f,-0.3673f,-0.821f,1.0117f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.1249f,-0.0256f,0.0086f,-2.002f,-0.005f,0.6446f,-0.2159f,1.5828f,0f,-0.2377f,-0.5865f,0.8296f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2498f,-0.0116f,0.0034f,-1.0982f,-0.0099f,0.293f,-0.0864f,0.8773f,0f,-0.108f,-0.2346f,1.1691f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2498f,-0.0116f,0.0034f,-1.5932f,-0.0099f,0.293f,-0.0864f,0.7403f,0f,-0.108f,-0.2346f,1.2123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2498f,-0.014f,0.0034f,-1.7123f,-0.0099f,0.3516f,-0.0864f,0.5903f,0f,-0.1296f,-0.2346f,0.9993f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2498f,-0.0116f,0.0034f,-1.5863f,-0.0099f,0.293f,-0.0864f,0.5675f,0f,-0.108f,-0.2346f,0.7431f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6245f,-0.0163f,0.0086f,-1.2293f,-0.0248f,0.4102f,-0.2159f,1.0266f,0f,-0.1513f,-0.5865f,1.0456f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8119f,-0.0093f,0.0103f,-1.1611f,-0.0322f,0.2344f,-0.2591f,2.4595f,0f,-0.0864f,-0.7038f,0.5857f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8119f,-0.0303f,0.0103f,-1.1704f,-0.0322f,0.7618f,-0.2591f,2.6939f,0f,-0.2809f,-0.7038f,0.4993f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8743f,-0.0559f,-0.012f,-0.2464f,-0.0347f,1.4064f,0.3023f,-0.0966f,0f,0.5186f,-0.821f,-0.0903f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8743f,-0.0559f,0.012f,1.1136f,-0.0347f,1.4064f,-0.3023f,0.3073f,0f,-0.5186f,-0.821f,0.9252f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000492514,"py":-0.0024807263,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args