# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4988f,-0.0602f,0f,-0.1329f,-0.0602f,1.4988f,0f,3.3073f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7494f,-0.0301f,0f,0.6441f,-0.0301f,0.7494f,0f,2.6505f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7494f,-0.0301f,0f,-0.1053f,-0.0301f,0.7494f,0f,2.6204f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0616f,-0.0426f,0f,0.9639f,-0.0426f,1.0616f,0f,2.4757f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0616f,-0.0426f,0f,-0.0978f,-0.0426f,1.0616f,0f,2.433f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7494f,-0.0125f,0f,0.6642f,-0.0301f,0.3122f,0f,2.1509f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7494f,-0.0125f,0f,-0.0852f,-0.0301f,0.3122f,0f,2.1208f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8743f,-0.0251f,0f,-0.0601f,-0.0351f,0.6245f,0f,1.4963f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8743f,-0.0251f,0f,0.8141f,-0.0351f,0.6245f,0f,1.5314f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8118f,-0.0298f,-0.0121f,1.7773f,-0.0326f,0.7429f,0.3021f,2.4689f,0f,0.3276f,-0.6863f,0.1562f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8118f,-0.0092f,-0.0121f,1.7865f,-0.0326f,0.2286f,0.3021f,2.2403f,0f,0.1008f,-0.6863f,0.0554f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.1249f,-0.0252f,-0.0101f,2.005f,-0.005f,0.6286f,0.2518f,1.4729f,0f,0.2772f,-0.572f,-0.3546f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8743f,-0.039f,-0.0142f,1.889f,-0.0351f,0.9715f,0.3525f,1.2461f,0f,0.4284f,-0.8007f,-0.3158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6245f,-0.0161f,-0.0101f,1.7781f,-0.0251f,0.4f,0.2518f,0.8913f,0f,0.1764f,-0.572f,-0.6066f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2498f,-0.0115f,-0.004f,1.7281f,-0.01f,0.2857f,0.1007f,0.5779f,0f,0.126f,-0.2288f,-0.6754f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2498f,-0.0115f,-0.004f,1.2864f,-0.01f,0.2857f,0.1007f,0.6747f,0f,0.126f,-0.2288f,-0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2498f,-0.0138f,-0.004f,1.8513f,-0.01f,0.3429f,0.1007f,0.6265f,0f,0.1512f,-0.2288f,-0.9293f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2498f,-0.0115f,-0.004f,1.7201f,-0.01f,0.2857f,0.1007f,0.7793f,0f,0.126f,-0.2288f,-1.1329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8743f,-0.039f,0.0142f,-1.1258f,-0.0351f,0.9715f,-0.3525f,1.5537f,0f,-0.4284f,-0.8007f,1.1006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.1249f,-0.0252f,0.0101f,-2.005f,-0.005f,0.6286f,-0.2518f,1.6397f,0f,-0.2772f,-0.572f,0.9106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2498f,-0.0115f,0.004f,-1.1018f,-0.01f,0.2857f,-0.1007f,0.957f,0f,-0.126f,-0.2288f,1.2954f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2498f,-0.0115f,0.004f,-1.5969f,-0.01f,0.2857f,-0.1007f,0.8226f,0f,-0.126f,-0.2288f,1.3458f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2498f,-0.0138f,0.004f,-1.7154f,-0.01f,0.3429f,-0.1007f,0.6598f,0f,-0.1512f,-0.2288f,1.1422f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2498f,-0.0115f,0.004f,-1.5888f,-0.01f,0.2857f,-0.1007f,0.6212f,0f,-0.126f,-0.2288f,0.8882f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6245f,-0.0161f,0.0101f,-1.2326f,-0.0251f,0.4f,-0.2518f,1.0983f,0f,-0.1764f,-0.572f,1.1626f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8118f,-0.0092f,0.0121f,-1.1638f,-0.0326f,0.2286f,-0.3021f,2.5f,0f,-0.1008f,-0.6863f,0.615f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8118f,-0.0298f,0.0121f,-1.173f,-0.0326f,0.7429f,-0.3021f,2.7286f,0f,-0.3276f,-0.6863f,0.5143f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8743f,-0.0551f,-0.0142f,-0.2466f,-0.0351f,1.3716f,0.3525f,-0.0921f,0f,0.6048f,-0.8007f,-0.1845f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8743f,-0.0551f,0.0142f,1.1109f,-0.0351f,1.3716f,-0.3525f,0.3713f,0f,-0.6048f,-0.8007f,0.9998f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000503503,"py":-0.002508237,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args