# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4995f,-0.0385f,0f,-0.0851f,-0.0385f,1.4995f,0f,3.3098f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7498f,-0.0193f,0f,0.6823f,-0.0193f,0.7498f,0f,2.6418f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7498f,-0.0193f,0f,-0.0674f,-0.0193f,0.7498f,0f,2.6225f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0621f,-0.0273f,0f,0.9996f,-0.0273f,1.0621f,0f,2.4624f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0621f,-0.0273f,0f,-0.0626f,-0.0273f,1.0621f,0f,2.4351f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7498f,-0.008f,0f,0.6952f,-0.0193f,0.3124f,0f,2.142f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7498f,-0.008f,0f,-0.0546f,-0.0193f,0.3124f,0f,2.1227f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8747f,-0.0161f,0f,-0.0385f,-0.0225f,0.6248f,0f,1.4979f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8747f,-0.0161f,0f,0.8362f,-0.0225f,0.6248f,0f,1.5204f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8122f,-0.0202f,-0.0049f,1.8115f,-0.0209f,0.7857f,0.1902f,2.4957f,0f,0.2061f,-0.7255f,0.2477f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8122f,-0.0062f,-0.0049f,1.8177f,-0.0209f,0.2417f,0.1902f,2.254f,0f,0.0634f,-0.7255f,0.1842f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.125f,-0.0171f,-0.0041f,2.0265f,-0.0032f,0.6648f,0.1585f,1.4285f,0f,0.1744f,-0.6046f,-0.0982f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8747f,-0.0264f,-0.0057f,1.907f,-0.0225f,1.0274f,0.2219f,1.2123f,0f,0.2695f,-0.8464f,-0.0248f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6248f,-0.0109f,-0.0041f,1.7921f,-0.0161f,0.4231f,0.1585f,0.8178f,0f,0.111f,-0.6046f,-0.2567f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2499f,-0.0078f,-0.0016f,1.7378f,-0.0064f,0.3022f,0.0634f,0.4981f,0f,0.0793f,-0.2418f,-0.2755f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2499f,-0.0078f,-0.0016f,1.2973f,-0.0064f,0.3022f,0.0634f,0.6078f,0f,0.0793f,-0.2418f,-0.2438f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2499f,-0.0093f,-0.0016f,1.8626f,-0.0064f,0.3626f,0.0634f,0.5043f,0f,0.0951f,-0.2418f,-0.5332f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2499f,-0.0078f,-0.0016f,1.7345f,-0.0064f,0.3022f,0.0634f,0.6249f,0f,0.0793f,-0.2418f,-0.7592f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8747f,-0.0264f,0.0057f,-1.099f,-0.0225f,1.0274f,-0.2219f,1.4047f,0f,-0.2695f,-0.8464f,0.8651f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.125f,-0.0171f,0.0041f,-1.9775f,-0.0032f,0.6648f,-0.1585f,1.5318f,0f,-0.1744f,-0.6046f,0.6966f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2499f,-0.0078f,0.0016f,-1.083f,-0.0064f,0.3022f,-0.0634f,0.7845f,0f,-0.0793f,-0.2418f,0.9631f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2499f,-0.0078f,0.0016f,-1.5798f,-0.0064f,0.3022f,-0.0634f,0.6508f,0f,-0.0793f,-0.2418f,0.9949f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2499f,-0.0093f,0.0016f,-1.7015f,-0.0064f,0.3626f,-0.0634f,0.5237f,0f,-0.0951f,-0.2418f,0.7689f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2499f,-0.0078f,0.0016f,-1.5765f,-0.0064f,0.3022f,-0.0634f,0.524f,0f,-0.0793f,-0.2418f,0.5112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6248f,-0.0109f,0.0041f,-1.2122f,-0.0161f,0.4231f,-0.1585f,0.9467f,0f,-0.111f,-0.6046f,0.8551f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8122f,-0.0062f,0.0049f,-1.125f,-0.0209f,0.2417f,-0.1902f,2.4163f,0f,-0.0634f,-0.7255f,0.5351f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8122f,-0.0202f,0.0049f,-1.1312f,-0.0209f,0.7857f,-0.1902f,2.658f,0f,-0.2061f,-0.7255f,0.4717f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8747f,-0.0373f,-0.0057f,-0.2478f,-0.0225f,1.4505f,0.2219f,-0.0878f,0f,0.3805f,-0.8464f,0.0565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8747f,-0.0373f,0.0057f,1.1201f,-0.0225f,1.4505f,-0.2219f,0.2031f,0f,-0.3805f,-0.8464f,0.8016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000206251,"py":-0.0016055263,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args