# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4998f,-0.0217f,0f,-0.0479f,-0.0217f,1.4998f,0f,3.3113f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7499f,-0.0108f,0f,0.712f,-0.0108f,0.7499f,0f,2.6347f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7499f,-0.0108f,0f,-0.0379f,-0.0108f,0.7499f,0f,2.6238f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0624f,-0.0154f,0f,1.0272f,-0.0154f,1.0624f,0f,2.4517f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0624f,-0.0154f,0f,-0.0352f,-0.0154f,1.0624f,0f,2.4363f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7499f,-0.0045f,0f,0.7192f,-0.0108f,0.3125f,0f,2.1347f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7499f,-0.0045f,0f,-0.0307f,-0.0108f,0.3125f,0f,2.1239f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8749f,-0.009f,0f,-0.0217f,-0.0126f,0.6249f,0f,1.4989f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8749f,-0.009f,0f,0.8532f,-0.0126f,0.6249f,0f,1.5116f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8124f,-0.0116f,-0.0015f,1.8387f,-0.0117f,0.805f,0.1008f,2.5252f,0f,0.1092f,-0.7432f,0.3117f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8124f,-0.0036f,-0.0015f,1.8423f,-0.0117f,0.2477f,0.1008f,2.2775f,0f,0.0336f,-0.7432f,0.278f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.125f,-0.0098f,-0.0012f,2.0422f,-0.0018f,0.6812f,0.084f,1.4216f,0f,0.0924f,-0.6193f,0.0985f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8749f,-0.0152f,-0.0017f,1.9201f,-0.0126f,1.0527f,0.1176f,1.2172f,0f,0.1428f,-0.8671f,0.1971f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6249f,-0.0063f,-0.0012f,1.8011f,-0.009f,0.4335f,0.084f,0.7988f,0f,0.0588f,-0.6193f,0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.25f,-0.0045f,-0.0005f,1.7432f,-0.0036f,0.3096f,0.0336f,0.4798f,0f,0.042f,-0.2477f,0.0344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.25f,-0.0045f,-0.0005f,1.304f,-0.0036f,0.3096f,0.0336f,0.5973f,0f,0.042f,-0.2477f,0.0512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.25f,-0.0054f,-0.0005f,1.8686f,-0.0036f,0.3716f,0.0336f,0.4533f,0f,0.0504f,-0.2477f,-0.2217f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.25f,-0.0045f,-0.0005f,1.7423f,-0.0036f,0.3096f,0.0336f,0.547f,0f,0.042f,-0.2477f,-0.4611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8749f,-0.0152f,0.0017f,-1.0816f,-0.0126f,1.0527f,-0.1176f,1.3167f,0f,-0.1428f,-0.8671f,0.6682f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.125f,-0.0098f,0.0012f,-1.959f,-0.0018f,0.6812f,-0.084f,1.473f,0f,-0.0924f,-0.6193f,0.5191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.25f,-0.0045f,0.0005f,-1.0726f,-0.0036f,0.3096f,-0.0336f,0.689f,0f,-0.042f,-0.2477f,0.6903f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.25f,-0.0045f,0.0005f,-1.5707f,-0.0036f,0.3096f,-0.0336f,0.558f,0f,-0.042f,-0.2477f,0.7071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.25f,-0.0054f,0.0005f,-1.6943f,-0.0036f,0.3716f,-0.0336f,0.4606f,0f,-0.0504f,-0.2477f,0.4678f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.25f,-0.0045f,0.0005f,-1.5698f,-0.0036f,0.3096f,-0.0336f,0.4908f,0f,-0.042f,-0.2477f,0.2116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6249f,-0.0063f,0.0012f,-1.2001f,-0.009f,0.4335f,-0.084f,0.8646f,0f,-0.0588f,-0.6193f,0.6032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8124f,-0.0036f,0.0015f,-1.0967f,-0.0117f,0.2477f,-0.1008f,2.361f,0f,-0.0336f,-0.7432f,0.4634f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8124f,-0.0116f,0.0015f,-1.1003f,-0.0117f,0.805f,-0.1008f,2.6088f,0f,-0.1092f,-0.7432f,0.4298f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8749f,-0.0215f,-0.0017f,-0.2492f,-0.0126f,1.4862f,0.1176f,-0.0587f,0f,0.2016f,-0.8671f,0.2397f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8749f,-0.0215f,0.0017f,1.1237f,-0.0126f,1.4862f,-0.1176f,0.0962f,0f,-0.2016f,-0.8671f,0.6346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000065262,"py":-0.0009031765,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args