# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4998f,0.0217f,0f,0.0479f,0.0217f,1.4998f,0f,3.3131f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7499f,0.0108f,0f,0.7879f,0.0108f,0.7499f,0f,2.6148f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7499f,0.0108f,0f,0.0379f,0.0108f,0.7499f,0f,2.6256f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0624f,0.0154f,0f,1.0976f,0.0154f,1.0624f,0f,2.4228f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0624f,0.0154f,0f,0.0352f,0.0154f,1.0624f,0f,2.4381f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7499f,0.0045f,0f,0.7806f,0.0108f,0.3125f,0f,2.1148f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7499f,0.0045f,0f,0.0307f,0.0108f,0.3125f,0f,2.1257f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8749f,0.009f,0f,0.0217f,0.0126f,0.6249f,0f,1.5007f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8749f,0.009f,0f,0.8966f,0.0126f,0.6249f,0f,1.4881f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8124f,0.0116f,-0.0015f,1.9129f,0.0117f,0.805f,-0.1008f,2.6072f,0f,-0.1092f,-0.7432f,0.4293f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8124f,0.0036f,-0.0015f,1.9093f,0.0117f,0.2477f,-0.1008f,2.3595f,0f,-0.0336f,-0.7432f,0.4629f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.125f,0.0098f,-0.0012f,2.0841f,0.0018f,0.6812f,-0.084f,1.4814f,0f,-0.0924f,-0.6193f,0.5186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8749f,0.0152f,-0.0017f,1.9567f,0.0126f,1.0527f,-0.1176f,1.3143f,0f,-0.1428f,-0.8671f,0.6676f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6249f,0.0063f,-0.0012f,1.8252f,0.009f,0.4335f,-0.084f,0.8658f,0f,-0.0588f,-0.6193f,0.6026f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.25f,0.0045f,-0.0005f,1.7583f,0.0036f,0.3096f,-0.0336f,0.5655f,0f,-0.042f,-0.2477f,0.7065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.25f,0.0045f,-0.0005f,1.3227f,0.0036f,0.3096f,-0.0336f,0.6956f,0f,-0.042f,-0.2477f,0.6897f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.25f,0.0054f,-0.0005f,1.882f,0.0036f,0.3716f,-0.0336f,0.4681f,0f,-0.0504f,-0.2477f,0.4672f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.25f,0.0045f,-0.0005f,1.7574f,0.0036f,0.3096f,-0.0336f,0.4983f,0f,-0.042f,-0.2477f,0.2111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8749f,0.0152f,0.0017f,-1.0451f,0.0126f,1.0527f,0.1176f,1.2148f,0f,0.1428f,-0.8671f,0.1977f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.125f,0.0098f,0.0012f,-1.917f,0.0018f,0.6812f,0.084f,1.43f,0f,0.0924f,-0.6193f,0.0991f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.25f,0.0045f,0.0005f,-1.0539f,0.0036f,0.3096f,0.0336f,0.6039f,0f,0.042f,-0.2477f,0.0518f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.25f,0.0045f,0.0005f,-1.5556f,0.0036f,0.3096f,0.0336f,0.4873f,0f,0.042f,-0.2477f,0.035f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.25f,0.0054f,0.0005f,-1.681f,0.0036f,0.3716f,0.0336f,0.4608f,0f,0.0504f,-0.2477f,-0.2212f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.25f,0.0045f,0.0005f,-1.5547f,0.0036f,0.3096f,0.0336f,0.5545f,0f,0.042f,-0.2477f,-0.4605f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6249f,0.0063f,0.0012f,-1.1761f,0.009f,0.4335f,0.084f,0.7999f,0f,0.0588f,-0.6193f,0.015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8124f,0.0036f,0.0015f,-1.0297f,0.0117f,0.2477f,0.1008f,2.2759f,0f,0.0336f,-0.7432f,0.2786f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8124f,0.0116f,0.0015f,-1.0261f,0.0117f,0.805f,0.1008f,2.5237f,0f,0.1092f,-0.7432f,0.3122f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8749f,0.0215f,-0.0017f,-0.2488f,0.0126f,1.4862f,-0.1176f,0.0848f,0f,-0.2016f,-0.8671f,0.6262f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8749f,0.0215f,0.0017f,1.1241f,0.0126f,1.4862f,0.1176f,-0.0689f,0f,0.2016f,-0.8671f,0.2313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000065262,"py":0.0009031765,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args