# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4995f,0.0385f,0f,0.0851f,0.0385f,1.4995f,0f,3.313f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7498f,0.0193f,0f,0.8172f,0.0193f,0.7498f,0f,2.6065f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7498f,0.0193f,0f,0.0675f,0.0193f,0.7498f,0f,2.6257f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0621f,0.0273f,0f,1.1248f,0.0273f,1.0621f,0f,2.411f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0621f,0.0273f,0f,0.0626f,0.0273f,1.0621f,0f,2.4383f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7498f,0.008f,0f,0.8044f,0.0193f,0.3124f,0f,2.1066f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7498f,0.008f,0f,0.0546f,0.0193f,0.3124f,0f,2.1259f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8747f,0.0161f,0f,0.0386f,0.0225f,0.6248f,0f,1.5011f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8747f,0.0161f,0f,0.9133f,0.0225f,0.6248f,0f,1.4786f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8122f,0.0202f,-0.0049f,1.9439f,0.0209f,0.7857f,-0.1902f,2.6562f,0f,-0.2061f,-0.7255f,0.4696f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8122f,0.0062f,-0.0049f,1.9376f,0.0209f,0.2417f,-0.1902f,2.4144f,0f,-0.0634f,-0.7255f,0.533f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.125f,0.0171f,-0.0041f,2.1029f,0.0032f,0.6648f,-0.1585f,1.5477f,0f,-0.1744f,-0.6046f,0.6945f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8747f,0.0264f,-0.0057f,1.9741f,0.0225f,1.0274f,-0.2219f,1.4013f,0f,-0.2695f,-0.8464f,0.863f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6248f,0.0109f,-0.0041f,1.8375f,0.0161f,0.4231f,-0.1585f,0.9497f,0f,-0.111f,-0.6046f,0.8531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2499f,0.0078f,-0.0016f,1.7676f,0.0064f,0.3022f,-0.0634f,0.665f,0f,-0.0793f,-0.2418f,0.9928f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2499f,0.0078f,-0.0016f,1.3334f,0.0064f,0.3022f,-0.0634f,0.7971f,0f,-0.0793f,-0.2418f,0.9611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2499f,0.0093f,-0.0016f,1.8894f,0.0064f,0.3626f,-0.0634f,0.538f,0f,-0.0951f,-0.2418f,0.7668f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2499f,0.0078f,-0.0016f,1.7644f,0.0064f,0.3022f,-0.0634f,0.5382f,0f,-0.0793f,-0.2418f,0.5092f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8747f,0.0264f,0.0057f,-1.0318f,0.0225f,1.0274f,0.2219f,1.2089f,0f,0.2695f,-0.8464f,-0.0228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.125f,0.0171f,0.0041f,-1.901f,0.0032f,0.6648f,0.1585f,1.4444f,0f,0.1744f,-0.6046f,-0.0961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2499f,0.0078f,0.0016f,-1.0469f,0.0064f,0.3022f,0.0634f,0.6204f,0f,0.0793f,-0.2418f,-0.2418f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2499f,0.0078f,0.0016f,-1.5499f,0.0064f,0.3022f,0.0634f,0.5124f,0f,0.0793f,-0.2418f,-0.2735f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2499f,0.0093f,0.0016f,-1.6748f,0.0064f,0.3626f,0.0634f,0.5186f,0f,0.0951f,-0.2418f,-0.5312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2499f,0.0078f,0.0016f,-1.5466f,0.0064f,0.3022f,0.0634f,0.6392f,0f,0.0793f,-0.2418f,-0.7571f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6248f,0.0109f,0.0041f,-1.1668f,0.0161f,0.4231f,0.1585f,0.8208f,0f,0.111f,-0.6046f,-0.2547f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8122f,0.0062f,0.0049f,-1.005f,0.0209f,0.2417f,0.1902f,2.2522f,0f,0.0634f,-0.7255f,0.1863f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8122f,0.0202f,0.0049f,-0.9988f,0.0209f,0.7857f,0.1902f,2.4939f,0f,0.2061f,-0.7255f,0.2497f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8747f,0.0373f,-0.0057f,-0.2454f,0.0225f,1.4505f,-0.2219f,0.1818f,0f,-0.3805f,-0.8464f,0.7858f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8747f,0.0373f,0.0057f,1.1227f,0.0225f,1.4505f,0.2219f,-0.105f,0f,0.3805f,-0.8464f,0.0406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000206251,"py":0.0016055263,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args