# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4991f,0.0506f,0f,0.1117f,0.0506f,1.4991f,0f,3.3127f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7496f,0.0253f,0f,0.8381f,0.0253f,0.7496f,0f,2.6003f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7496f,0.0253f,0f,0.0885f,0.0253f,0.7496f,0f,2.6256f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0619f,0.0358f,0f,1.1441f,0.0358f,1.0619f,0f,2.4024f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0619f,0.0358f,0f,0.0822f,0.0358f,1.0619f,0f,2.4382f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7496f,0.0105f,0f,0.8213f,0.0253f,0.3123f,0f,2.1006f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7496f,0.0105f,0f,0.0717f,0.0253f,0.3123f,0f,2.1259f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8745f,0.0211f,0f,0.0506f,0.0295f,0.6246f,0f,1.5013f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8745f,0.0211f,0f,0.9251f,0.0295f,0.6246f,0f,1.4718f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.812f,0.0257f,-0.0087f,1.9671f,0.0274f,0.762f,-0.2591f,2.6997f,0f,-0.2809f,-0.7038f,0.4954f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.812f,0.0079f,-0.0087f,1.9592f,0.0274f,0.2345f,-0.2591f,2.4652f,0f,-0.0864f,-0.7038f,0.5818f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.1249f,0.0217f,-0.0073f,2.1182f,0.0042f,0.6447f,-0.2159f,1.6167f,0f,-0.2377f,-0.5865f,0.8257f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8745f,0.0336f,-0.0102f,1.9888f,0.0295f,0.9964f,-0.3023f,1.4883f,0f,-0.3673f,-0.821f,1.0078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6246f,0.0138f,-0.0073f,1.8485f,0.0211f,0.4103f,-0.2159f,1.039f,0f,-0.1513f,-0.5865f,1.0418f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2499f,0.0099f,-0.0029f,1.7769f,0.0084f,0.2931f,-0.0864f,0.7696f,0f,-0.108f,-0.2346f,1.2085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2499f,0.0099f,-0.0029f,1.3436f,0.0084f,0.2931f,-0.0864f,0.9016f,0f,-0.108f,-0.2346f,1.1652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2499f,0.0119f,-0.0029f,1.897f,0.0084f,0.3517f,-0.0864f,0.6204f,0f,-0.1296f,-0.2346f,0.9955f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2499f,0.0099f,-0.0029f,1.7711f,0.0084f,0.2931f,-0.0864f,0.5969f,0f,-0.108f,-0.2346f,0.7393f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8745f,0.0336f,0.0102f,-1.0219f,0.0295f,0.9964f,0.3023f,1.2223f,0f,0.3673f,-0.821f,-0.1983f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.1249f,0.0217f,0.0073f,-1.889f,0.0042f,0.6447f,0.2159f,1.4708f,0f,0.2377f,-0.5865f,-0.2508f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2499f,0.0099f,0.0029f,-1.041f,0.0084f,0.2931f,0.0864f,0.6578f,0f,0.108f,-0.2346f,-0.473f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2499f,0.0099f,0.0029f,-1.5446f,0.0084f,0.2931f,0.0864f,0.5574f,0f,0.108f,-0.2346f,-0.5163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2499f,0.0119f,0.0029f,-1.6686f,0.0084f,0.3517f,0.0864f,0.5894f,0f,0.1296f,-0.2346f,-0.7725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2499f,0.0099f,0.0029f,-1.5388f,0.0084f,0.2931f,0.0864f,0.7302f,0f,0.108f,-0.2346f,-0.9854f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6246f,0.0138f,0.0073f,-1.1592f,0.0211f,0.4103f,0.2159f,0.8594f,0f,0.1513f,-0.5865f,-0.4669f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.812f,0.0079f,0.0087f,-0.9876f,0.0274f,0.2345f,0.2591f,2.2403f,0f,0.0864f,-0.7038f,0.1103f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.812f,0.0257f,0.0087f,-0.9797f,0.0274f,0.762f,0.2591f,2.4748f,0f,0.2809f,-0.7038f,0.1968f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8745f,0.0475f,-0.0102f,-0.241f,0.0295f,1.4067f,-0.3023f,0.2719f,0f,-0.5186f,-0.821f,0.9036f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8745f,0.0475f,0.0102f,1.1217f,0.0295f,1.4067f,0.3023f,-0.1161f,0f,0.5186f,-0.821f,-0.1119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000355286,"py":0.0021070857,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args