# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [-1.4989f,0.0578f,0f,0.1277f,0.0578f,1.4989f,0f,3.3124f,0f,0f,-1.25f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display1) {transformation: [-0.7494f,0.0289f,0f,0.8506f,0.0289f,0.7494f,0f,2.5966f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display2) {transformation: [-0.7494f,0.0289f,0f,0.1012f,0.0289f,0.7494f,0f,2.6255f,0f,0f,-0.5f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display3) {transformation: [-1.0617f,0.0409f,0f,1.1557f,0.0409f,1.0617f,0f,2.3972f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display4) {transformation: [-1.0617f,0.0409f,0f,0.094f,0.0409f,1.0617f,0f,2.4381f,0f,0f,-1f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display10) {transformation: [-0.7494f,0.012f,0f,0.8314f,0.0289f,0.3123f,0f,2.0969f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display8) {transformation: [-0.7494f,0.012f,0f,0.0819f,0.0289f,0.3123f,0f,2.1258f,0f,0f,-0.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display24) {transformation: [-0.8744f,0.0241f,0f,0.0578f,0.0337f,0.6245f,0f,1.5013f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display23) {transformation: [-0.8744f,0.0241f,0f,0.9322f,0.0337f,0.6245f,0f,1.4676f,0f,0f,-0.875f,0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display5) {transformation: [-0.8119f,0.0286f,-0.0116f,1.9816f,0.0313f,0.743f,-0.3022f,2.7293f,0f,-0.3276f,-0.6863f,0.5089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display25) {transformation: [-0.8119f,0.0088f,-0.0116f,1.9728f,0.0313f,0.2286f,-0.3022f,2.5007f,0f,-0.1008f,-0.6863f,0.6097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display7) {transformation: [-0.1249f,0.0242f,-0.0097f,2.1283f,0.0048f,0.6287f,-0.2518f,1.6682f,0f,-0.2772f,-0.572f,0.9053f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display6) {transformation: [-0.8744f,0.0375f,-0.0136f,1.9987f,0.0337f,0.9716f,-0.3525f,1.5519f,0f,-0.4284f,-0.8007f,1.0953f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display9) {transformation: [-0.6245f,0.0154f,-0.0097f,1.8565f,0.0241f,0.4001f,-0.2518f,1.1063f,0f,-0.1764f,-0.572f,1.1573f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display11) {transformation: [-0.2498f,0.011f,-0.0039f,1.784f,0.0096f,0.2858f,-0.1007f,0.8481f,0f,-0.126f,-0.2288f,1.3405f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display14) {transformation: [-0.2498f,0.011f,-0.0039f,1.3512f,0.0096f,0.2858f,-0.1007f,0.9792f,0f,-0.126f,-0.2288f,1.2901f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display12) {transformation: [-0.2498f,0.0132f,-0.0039f,1.9028f,0.0096f,0.3429f,-0.1007f,0.6854f,0f,-0.1512f,-0.2288f,1.1369f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display13) {transformation: [-0.2498f,0.011f,-0.0039f,1.7762f,0.0096f,0.2858f,-0.1007f,0.6466f,0f,-0.126f,-0.2288f,0.8829f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display16) {transformation: [-0.8744f,0.0375f,0.0136f,-1.0155f,0.0337f,0.9716f,0.3525f,1.2394f,0f,0.4284f,-0.8007f,-0.3105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display18) {transformation: [-0.1249f,0.0242f,0.0097f,-1.8813f,0.0048f,0.6287f,0.2518f,1.4949f,0f,0.2772f,-0.572f,-0.3493f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display20) {transformation: [-0.2498f,0.011f,0.0039f,-1.0366f,0.0096f,0.2858f,0.1007f,0.6931f,0f,0.126f,-0.2288f,-0.6197f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display19) {transformation: [-0.2498f,0.011f,0.0039f,-1.5407f,0.0096f,0.2858f,0.1007f,0.598f,0f,0.126f,-0.2288f,-0.6701f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display21) {transformation: [-0.2498f,0.0132f,0.0039f,-1.6639f,0.0096f,0.3429f,0.1007f,0.6464f,0f,0.1512f,-0.2288f,-0.924f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display22) {transformation: [-0.2498f,0.011f,0.0039f,-1.5329f,0.0096f,0.2858f,0.1007f,0.7994f,0f,0.126f,-0.2288f,-1.1276f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display17) {transformation: [-0.6245f,0.0154f,0.0097f,-1.1539f,0.0241f,0.4001f,0.2518f,0.8945f,0f,0.1764f,-0.572f,-0.6013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display26) {transformation: [-0.8119f,0.0088f,0.0116f,-0.9771f,0.0313f,0.2286f,0.3022f,2.2362f,0f,0.1008f,-0.6863f,0.0607f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display15) {transformation: [-0.8119f,0.0286f,0.0116f,-0.9683f,0.0313f,0.743f,0.3022f,2.4648f,0f,0.3276f,-0.6863f,0.1615f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display27) {transformation: [-0.8744f,0.0529f,-0.0136f,-0.2373f,0.0337f,1.3717f,-0.3525f,0.3354f,0f,-0.6048f,-0.8007f,0.9746f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(block_display28) {transformation: [-0.8744f,0.0529f,0.0136f,1.1213f,0.0337f,1.3717f,0.3525f,-0.1152f,0f,0.6048f,-0.8007f,-0.2097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"locator":{"px":0.0000464033,"py":0.0024079583,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args