# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage rd_models:blackstone_golem rig_hash set value '38a38e23ffdfdbfd7f83e9be63c6c9b18e75069f8303b339757e246d787fc87b'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.stomp.frame dummy